name: 'Release Bot'
description: 'Automated release management using release-tool'
inputs:
  command:
    description: 'Command to run (generate, publish, update)'
    required: false
  version:
    description: 'Version argument for the command'
    required: false
  new_version_type:
    description: 'Auto-bump type (patch, minor, major, rc)'
    required: false
  from_version:
    description: 'Compare from this version'
    required: false
  force:
    description: 'Force overwrite (none, draft, published)'
    required: false
    default: 'none'
  debug:
    description: 'Enable debug output'
    required: false
    default: 'false'
  github_token:
    description: 'GitHub Token'
    required: true
  config_path:
    description: 'Path to release_tool.toml'
    required: false
    default: '.release_tool.toml'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
    INPUT_COMMAND: ${{ inputs.command }}
    INPUT_VERSION: ${{ inputs.version }}
    INPUT_NEW_VERSION_TYPE: ${{ inputs.new_version_type }}
    INPUT_FROM_VERSION: ${{ inputs.from_version }}
    INPUT_FORCE: ${{ inputs.force }}
    INPUT_DEBUG: ${{ inputs.debug }}
    INPUT_CONFIG_PATH: ${{ inputs.config_path }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    GITHUB_WORKSPACE: ${{ github.workspace }}
    GITHUB_EVENT_PATH: ${{ github.event_path }}
    GITHUB_EVENT_NAME: ${{ github.event_name }}
    GITHUB_REPOSITORY: ${{ github.repository }}
    GITHUB_REF_NAME: ${{ github.ref_name }}
